name: flutter_ex
description: "App for management money expenses."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  package_info_plus: ^5.0.1
  email_validator: ^2.1.17
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

flutter:
  assets:
    - lib/resources/drawables/
  fonts:
    - family: Poppins
      fonts:
        - asset: lib/resources/fonts/Poppins-Regular.ttf
        - asset: lib/resources/fonts/Poppins-SemiBold.ttf
          weight: 600
  generate: true
  uses-material-design: true
