name: flutter_ex
description: "App for management money expenses."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  package_info_plus: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: Poppins
      fonts:
        - asset: resources/fonts/Poppins-Regular.ttf
        - asset: resources/fonts/Poppins-SemiBold.ttf
          weight: 600
  generate: true
  uses-material-design: true
